sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tL8FcSJQdHoZUYto2nA
    access-key-secret: 7a2fl1ktHS7DeVnmLJzRT7CwJlytPu
    bucket-name: xiaoxiangzhu
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
